### ISSUE TITLE
Preview not updating

### ISSUE THREAD

**Issue by ArunNairID** [pixelkind/p5canvas#1]
The preview is not updating on change of methods or functions. The canvas has to be closed and then reopened .

Sample Code:

Example:
function setup() {
    createCanvas(640, 480);
  }
  
  function draw() {
    if (mouseIsPressed) {
      fill(0);
    } else {
      fill(255);
    }
    ellipse(mouseX, mouseY, 80, 80); ///changing this to new shape  **_rect_** doesnt update the preview.

    
  }

**Comment by pixelkind** [comment]
Thank you, I will have a look :)

**Comment by pixelkind** [comment]
The bug is fixed in version 1.0.2 and thanks again for your help 👍
