### ISSUE TITLE
Moving Tab p5canvas from split to toggle breaks with error

### ISSUE THREAD

**Issue by carloshm** [pixelkind/p5canvas#11]
When moving p5canvas tab from split to toggle view throws an error:
"Unable to open 'p5canvas': ModelService: Cannot add model because it already exists!."
when clicking to recover view.

video upload

![vscode sktech p5canvas](https://user-images.githubusercontent.com/2389573/50568362-ee6a4f00-0d50-11e9-8660-b675b1bd2470.gif)

**Comment by pixelkind** [comment]
Added a workaround in the latest release, making it possible to re-open the p5canvas
