### ISSUE TITLE
vscode.previewHtml deprecated

### ISSUE THREAD

**Issue by athelas64** [pixelkind/p5canvas#13]
Hi,
just got a warning in the insiders version of VS Code that the extension is using a deprecated command that will soon be removed. https://screenpresso.com/=VJn7e
I just want to ask if there is possibility that this great extension will keep functioning in the future. Thank you!

**Comment by pixelkind** [comment]
Hej,
thank you for your feedback. I am working on it, to replace it 😃

**Comment by dbelyaev** [comment]
@pixelkind can't wait an updated version! thanks for you work! 👍

**Comment by pixelkind** [comment]
Hej @athelas64 and @dbelyaev, I have just published a first version, will need some clean up, but would be happy if you could provide some feedback if everything works as expected.

**Comment by athelas64** [comment]
Hi, thanks so much! In the last builds of VSCode p5canvas was not working, at the moment it behaves OK, I will be doing some lessons with it in the coming days and will let you know if me or kids will successfully manage to break anything.

**Comment by pixelkind** [comment]
Would be super happy to hear about how you use it @athelas64 :) Will work on in the coming weeks to make it more smooth.

**Comment by athelas64** [comment]
Despite the existence of https://editor.p5js.org/ I still prefer p5canvas with VisualStudio, because I can use full editor capabilities when editing and live previewing the code. So, to me, it is still very relevant. 
Kids really love the live preview with auto updates and they constantly come up with all creative ways how to "abuse it". To the large extend, this is very much supported as it makes teaching programming really fun and let them learn by experimenting.
p5canvas helps with the transition from drag and drop graphical programming {Scratch) into the big game. I wish more educators would be using it!
