### ISSUE TITLE
Not sure what went wrong

### ISSUE THREAD

**Issue by jakearmendariz** [pixelkind/p5canvas#15]
I am not sure what the problem was and it may be my fault but I was just trying to open the canvas with a setup and draw function and than with nothing at all and 
<img width="562" alt="Screen Shot 2019-03-26 at 5 23 10 PM" src="https://user-images.githubusercontent.com/41457044/55041967-cbb4a300-4fec-11e9-9ee3-c0527f1af855.png"> I got this along with a message stating "An error occurred..." where the canvas should be. Thank you and I apologize if I set it up incorrectly.

**Comment by pixelkind** [comment]
Hej, you did everything right. I already work on the new API but haven't had the time to release ist. Usually, when this error appears, it helps to close the p5canvas and re-open it.
I will try to ship the new version this weekend.

**Comment by pixelkind** [comment]
Hej @jakearmendariz, I have just published a first version, will need some clean up, but would be happy if you could provide some feedback if everything works as expected.

**Comment by zero1ne-dev** [comment]
Does this p5canvas no longer work?
I wanted to run example code using p5canvas, but only black screen comes out.

<img width="1082" alt="Screenshot 2019-04-08 08 16 09" src="https://user-images.githubusercontent.com/1378925/55720220-48a73a00-5a3b-11e9-95af-d67878c72eac.png">

**Comment by pixelkind** [comment]
Hej @skycwy223, it should work. Can you create an extra issue and provide me with the example code? One thing I already see is that you want to use your own setup function, p5canvas creates a canvas for you, so you have not to write your own setup function and call createCanvas.
