### ISSUE TITLE
the plugin is  not support es6, what should i do for this problem?

### ISSUE THREAD

**Issue by xiatian12345** [pixelkind/p5canvas#22]
Line 1, col 1: 'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
Line 2, col 1: 'let' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
Line 7, col 8: 'let' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).

**Comment by pixelkind** [comment]
Hej, in the next version, es6 Support will be the default.
So long, a workaround is to enter

```
/* jslint esversion: 6 */
```

at the beginning of the file.
