### ISSUE TITLE
Couldn't find canvas windows to preview 

### ISSUE THREAD

**Issue by spiritualartsy** [pixelkind/p5canvas#27]
Sir, can u please mention the steps that a user needs to take to preview his work. I am done with the installation and there is only one option "P5Canvas Console" in the output tab but there is no other option to make side window to preview.

**Comment by spiritualartsy** [comment]
> Sir, can u please mention the steps that a user needs to take to preview his work. I am done with the installation and there is only one option "P5Canvas Console" in the output tab but there is no other option to make side window to preview.

Yeah, I found it. it was on bottom left side.

**Comment by pixelkind** [comment]
Great that you find it, I will add another option via Menu or something similiar.

**Comment by atipezda** [comment]
same here
![image](https://user-images.githubusercontent.com/43711283/68076733-fd7abd00-fdb8-11e9-926a-655471e084b9.png)

**Comment by pixelkind** [comment]
Hej @atipezda, do you have a JavaScript file open? Can you please share a full screenshot and maybe some more information about your steps?
Thanks, Garrit
