### ISSUE TITLE
how to access the p5 object ?

### ISSUE THREAD

**Issue by LBdN** [pixelkind/p5canvas#3]
In my code, I use the p5.Vector.add method. but when running the extension, I got a 

> mysetup(): Cannot read property 'sub' of undefined
> draw(): Cannot read property 'sub' of undefined

**Comment by pixelkind** [comment]
Hej, can you please provide me with an example?

I have tested the example from the [reference](https://p5js.org/reference/#/p5.Vector) and it works.

```javascript
var v1 = createVector(40, 50);
var v2 = createVector(20, 30);

ellipse(v1.x, v1.y, 50, 50);
ellipse(v2.x, v2.y, 50, 50);
v1.add(v2);
ellipse(v1.x, v1.y, 50, 50);
```

Best regards, Garrit

**Comment by LBdN** [comment]
I mean the static version of the methods like p5.Vector.add and
p5.Vector.sub not the sub method on the vector object.

like : let v3 = p5.Vector.add(v1, v2);

Sorry to have been vague.

Cordialement,
Lionel Barret,

**Comment by pixelkind** [comment]
Hej Lionel,

good news, this issue is solved in the next release 1.0.6.

Best regards and thanks for helping,
Garrit

**Comment by pixelkind** [comment]
I have just released a new Version. I would be happy to get some feedback from you, if everything works as expected.

**Comment by LBdN** [comment]
it works fine . thank you.

Cordialement,
Lionel Barret,
