### ISSUE TITLE
command 'extension.showCanvas' not found?

### ISSUE THREAD

**Issue by wardrobefanatic** [pixelkind/p5canvas#30]
Hi, I just installed the extension and this pop-up appears when I try to click the shortcut button?

**Comment by pixelkind** [comment]
Hej, can you give me some more informations? Which OS, which Version of VS Code and does the problem stay after restarting your computer? Thank you :)

**Comment by pixelkind** [comment]
Hej @wardrobefanatic, do you still have the problem?

**Comment by abecus** [comment]
hey @wardrobefanatic, if you have installed any other extension for p5 canvas disable them and restart the vs code. It worked for me, and see if it works for you.
