### ISSUE TITLE
Why background() is not working in setup()?

### ISSUE THREAD

**Issue by hunar1997** [pixelkind/p5canvas#33]
I installed the extension, all the commands in draw() works, but if i place e.g background(255) in setup(), it doesn't affect the display, but when i open the html file with my browser it works as expected
```
function setup() {
  createCanvas(500, 400);
  background(255,0,0);
}
function draw(){
}
```

**Comment by pixelkind** [comment]
Hej @hunar1997, there is a standard setup script included which set up the canvas. In one of the next versions you can add your own setup routine. For now the setup method can not be overridden and can not be used as in plain html.
