### ISSUE TITLE
swallows JS errors

### ISSUE THREAD

**Issue by ccoenen** [pixelkind/p5canvas#40]
suppose you have the following (intentionally faulty) script:

```js
rect(100,100,100,100);
gronkh();
rect(300,100,100,100);
```

p5canvas will draw one of the two, since the second line would be a "undefined is not a function" error or something to that effect.

My problem is, that this error gets discarded silently, so debugging this is harder.

**Comment by pixelkind** [comment]
Will be fixed in the next release.
