### ISSUE TITLE
setup function not working

### ISSUE THREAD

**Issue by archtaurus** [pixelkind/p5canvas#42]
setup function not working

**Comment by pixelkind** [comment]
Hej @archtaurus, as stated in the Readme:

> There is a standard setup script included which setups a full width/height canvas that will be resized automatically. In one of the next versions this will become optional.

So this is not a bug, but the feature to create a setup function yourself is on the roadmap.

**Comment by pixelkind** [comment]
@archtaurus I am just about to publish the latest version (1.7.0) of p5canvas, which will include this feature :)
