### ISSUE TITLE
createCanvas() note working properly

### ISSUE THREAD

**Issue by berkmtb** [pixelkind/p5canvas#55]
The displayed canvas size is not matching the value set in createCanvas(). For example, if I set createCanvas(200,200), console.log(width) shows 819 and console.log(height) shows 858. Any ideas? Fyi, I installed version 1.7.0 via the VS Code marketplace. Thanks in advance for taking a look. Here's some sample code:

`function setup() {
  createCanvas(200, 200);
  console.log(width);
  console.log(height);
}`

**Comment by pixelkind** [comment]
Hej @berkmtb,

Sorry for my delayed answer. This is a bug and I already have an idea how to fix it. Thanks for letting me know.
