### ISSUE TITLE
Getting P5.JS' friendly error system into the console

### ISSUE THREAD

**Issue by ccoenen** [pixelkind/p5canvas#57]
Recent versions of P5.js have excellent error messages. We should look into getting them into the console.

**Comment by ccoenen** [comment]
I just learned that this is called "Friendly Error System": https://github.com/processing/p5.js/blob/main/contributor_docs/friendly_error_system.md

**Comment by ccoenen** [comment]
I fiddled around with _fesLogger for a good long while, until I realized that minified p5 just strips the debug logging stuff.
I now included the full, unminified p5.js, and did no other modifications to p5canvas. This is the result:

![grafik](https://user-images.githubusercontent.com/124909/194907758-9b038413-862c-490f-b1ce-9b5d46663116.png)

**Comment by ccoenen** [comment]
I will now look into getting the filenames cleaner. Would you be fine with shipping full p5.js instead of minified @pixelkind?

**Comment by ccoenen** [comment]
whoopsie! it noticed!
![grafik](https://user-images.githubusercontent.com/124909/194910069-1094ba37-a6d7-4d10-a591-108c04b943d2.png)

**Comment by ccoenen** [comment]
getting somewhere :-)

![grafik](https://user-images.githubusercontent.com/124909/194913964-c0b59d9f-71b0-4a83-b0f5-c618fe8669a1.png)

**Comment by pixelkind** [comment]
Fixed thanks to you @ccoenen :)
