### ISSUE TITLE
width and height of the canvas is wrong

### ISSUE THREAD

**Issue by barbarerik** [pixelkind/p5canvas#60]
Hi there
Am i doing something wrong, or there is an issue with wrong canvas scale?
![image](https://user-images.githubusercontent.com/31472198/162325956-ca5c5e32-9f35-45fb-96fa-a1ddd1bca0b0.png)

**Comment by pixelkind** [comment]
Hej @barbarerik,

Unfortunately, this is a bug. Currently the width is set automatically to the full width of the window, not the actual width of the canvas. I will fix that as soon as possible.
