### ISSUE TITLE
Laggy canvas

### ISSUE THREAD

**Issue by sakgoyal** [pixelkind/p5canvas#62]
My animations and code run very laggy on the canvas, but when I run it online through the official editor, it runs much better. why is there a difference in performance/speed? I have encountered so many weird bugs because it runs slow on vscode but full speed in any browser or the online editor.

**Comment by pixelkind** [comment]
Hej @sakgoyal,
I haven't encountered these problems until now. Can you please post some example code and a link to the same code in the online editor?
Thanks

**Comment by sakgoyal** [comment]
I dont have that code anymore since I rewrote it completely. so I cant give an example anymore. if I encounter the problem again, I will reopen this issue.
but, now I have another issue
